import type { PaletteTemplate } from "./moduleCatalog";

export const DIN_RAIL_UNIT_PER_MODULE = 250;
export const DIN_RAIL_PADDING_X = 55;
export const MODULE_UNIT_WIDTH = 232.58;
export const MODULE_UNIT_MM_WIDTH = 17.5;
export const MODULE_PX_PER_MM = MODULE_UNIT_WIDTH / MODULE_UNIT_MM_WIDTH;
export const MODULE_UNIT_HEIGHT = Math.round(83 * MODULE_PX_PER_MM);

export type ModuleEntry = Omit<PaletteTemplate, "assetPath">;

export function svg300DpiPx(svgPixels: number): number {
  return Math.round(svgPixels * (25.4 / 300) * MODULE_PX_PER_MM * 100) / 100;
}

export const moduleEntries: ModuleEntry[] = [
  {
    templateId: "fr-1p-svg",
    code: "fr 1P",
    label: "fr 1P",
    type: "FR",
    category: "FR",
    deviceKind: "fr",
    phase: "L1",
    modules: 1,
    moduleRef: "FR/fr 1P.svg",
    frRatedCurrent: "63A",
  },
  {
    templateId: "fr-3p-svg",
    code: "FR",
    label: "FR",
    type: "FR",
    category: "FR",
    deviceKind: "fr",
    phase: "L1+L2+L3",
    modules: 3,
    moduleRef: "FR/FR.svg",
    placeholderDefaults: { LABEL: "63A" },
    frRatedCurrent: "63A",
  },
  {
    templateId: "spd-1p-svg",
    code: "SPD 1p",
    label: "SPD 1p",
    type: "SPD",
    category: "SPD",
    deviceKind: "spd",
    phase: "L1",
    modules: 1,
    moduleRef: "SPD/SPD 1p.svg",
    spdType: "T2",
    spdVoltage: 275,
    spdDischargeCurrent: 25,
  },
  {
    templateId: "spd-4p-svg",
    code: "SPD",
    label: "SPD",
    type: "SPD",
    category: "SPD",
    deviceKind: "spd",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "SPD/SPD.svg",
    spdType: "T1+T2",
    spdVoltage: 275,
    spdDischargeCurrent: 25,
  },
  {
    templateId: "rcd-2p-svg",
    code: "RCD 2P",
    label: "RCD 2P",
    type: "RCD",
    category: "RCD",
    deviceKind: "rcd",
    phase: "L1",
    modules: 2,
    moduleRef: "RCD/RCD 2P.svg",
    placeholderDefaults: { CURRENT: "40A" },
    rcdRatedCurrent: 40,
    rcdResidualCurrent: 30,
    rcdType: "A",
  },
  {
    templateId: "rcd-4p-svg",
    code: "RCD 4P",
    label: "RCD 4P",
    type: "RCD",
    category: "RCD",
    deviceKind: "rcd",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "RCD/RCD 4P.svg",
    placeholderDefaults: { CURRENT: "40A" },
    rcdRatedCurrent: 40,
    rcdResidualCurrent: 30,
    rcdType: "A",
  },
  {
    templateId: "mcb-1p-svg",
    code: "MCB 1P",
    label: "MCB 1P",
    type: "MCB",
    category: "MCB",
    deviceKind: "mcb",
    phase: "L1",
    modules: 1,
    moduleRef: "MCB/roz\u0142acznik nadpr\u0105dowy MCB 1P.svg",
    placeholderDefaults: { CURRENT: "B16" },
    protectionType: "B16",
    powerW: 2300,
  },
  {
    templateId: "mcb-2p-svg",
    code: "MCB 2P",
    label: "MCB 2P",
    type: "MCB",
    category: "MCB",
    deviceKind: "mcb",
    phase: "L1+L2",
    modules: 2,
    moduleRef: "MCB/roz\u0142acznik nadpr\u0105dowy MCB 2P.svg",
    placeholderDefaults: { CURRENT: "B16" },
    protectionType: "B16",
    powerW: 7200,
  },
  {
    templateId: "mcb-3p-svg",
    code: "MCB 3p",
    label: "MCB 3p",
    type: "MCB",
    category: "MCB",
    deviceKind: "mcb",
    phase: "L1+L2+L3",
    modules: 3,
    moduleRef: "MCB/roz\u0142acznik nadpr\u0105dowy MCB 3P.svg",
    placeholderDefaults: { CURRENT: "C16" },
    protectionType: "C16",
    powerW: 11000,
  },
  {
    templateId: "kontrolki-faz-svg",
    code: "Kontrolki faz",
    label: "Kontrolki faz",
    type: "Controls",
    category: "Controls",
    deviceKind: "phaseIndicator",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Kontrolki faz/Kontrolki faz.svg",
  },
  {
    templateId: "gniazdo-szyna-din-svg",
    code: "GNIAZDO SZYNA DIN",
    label: "GNIAZDO SZYNA DIN",
    type: "Inne",
    category: "Inne",
    deviceKind: "other",
    phase: "L1",
    modules: 2,
    moduleRef: "Inne/GNIAZDO SZYNA DIN.svg",
    circuitType: "Gniazdo",
  },
  {
    templateId: "listwa-12-pin-svg",
    code: "LISTWA 12 PIN",
    label: "LISTWA 12 PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Listwy zaciskowe/LISTWA 12 PIN.svg",
    customWidth: MODULE_UNIT_WIDTH,
    customHeight: MODULE_UNIT_HEIGHT,
  },
  {
    templateId: "listwa-zaciskowa-5pin-svg",
    code: "Listwa zaciskowa 5pin",
    label: "Listwa zaciskowa 5pin (3P+N+PE)",
    type: "Z\u0142\u0105cza",
    category: "Z\u0142\u0105cza",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 3,
    moduleRef: "zlacza/listwa-zaciskowa-5pin-3p-n-pe.svg",
  },
  {
    templateId: "zlacze-3xpen-svg",
    code: "Z\u0141\u0104CZE 3XPEN",
    label: "Z\u0141\u0104CZE 3XPEN",
    type: "Z\u0142\u0105cza",
    category: "Z\u0142\u0105cza",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 2,
    moduleRef: "zlacza/zlacze-3xpen.svg",
  },
];

export const currentModuleEntries: ModuleEntry[] = [
  {
    templateId: "fr-1p-new-svg",
    code: "Rozłącznik izolacyjny FR 1P",
    label: "Rozłącznik izolacyjny FR 1P",
    type: "FR",
    category: "FR",
    deviceKind: "fr",
    phase: "L1",
    modules: 1,
    moduleRef: "FR/Rozłącznik izolacyjny FR 1P.svg",
    frRatedCurrent: "63A",
  },
  {
    templateId: "fr-3p-new-svg",
    code: "Rozłącznik izolacyjny FR 3P",
    label: "Rozłącznik izolacyjny FR 3P",
    type: "FR",
    category: "FR",
    deviceKind: "fr",
    phase: "L1+L2+L3",
    modules: 3,
    moduleRef: "FR/Rozłącznik izolacyjny FR 3P.svg",
    frRatedCurrent: "63A",
  },
  {
    templateId: "spd-new-svg",
    code: "SPD",
    label: "SPD (Ogranicznik przepięć)",
    type: "SPD",
    category: "SPD",
    deviceKind: "spd",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "SPD/SPD.svg",
    spdType: "T1+T2",
    spdVoltage: 275,
    spdDischargeCurrent: 25,
  },

  {
    templateId: "blok-rozdzielczy-7pin-new-svg",
    code: "Blok rozdzielczy 4x7",
    label: "Blok rozdzielczy 4x7",
    type: "Blok rozdzielczy",
    category: "Blok rozdzielczy",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "Blok rozdzielczy/blok rozdzielczy 4x7.svg",
    // WHY: getPaletteTemplateDimensions already handles "blok rozdzielczy"
    // with the correct physical size (71mm wide, 97mm tall).
    // The SVG viewBox (202×276) does not carry DPI metadata, so svg300DpiPx
    // would give the wrong dimensions (~227 px = 1 module instead of 4).
  },
  {
    templateId: "kontrolki-faz-new-svg",
    code: "Kontrolki faz",
    label: "Kontrolki faz",
    type: "Controls",
    category: "Controls",
    deviceKind: "phaseIndicator",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Kontrolki faz/Kontrolki faz.svg",
  },
  {
    templateId: "przelacznik-sieci-3p-svg",
    code: "Przełącznik sieci 3P",
    label: "Przełącznik sieci 3P",
    type: "Przełącznik sieci",
    category: "Przełączniki sieci",
    deviceKind: "other",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "Przelaczniki sieci/Przelacznik sieci 3P.svg",
    customWidth: svg300DpiPx(1152),
    customHeight: svg300DpiPx(983),
  },
  {
    templateId: "przelacznik-sieci-4p-svg",
    code: "Przełącznik sieci 4P",
    label: "Przełącznik sieci 4P",
    type: "Przełącznik sieci",
    category: "Przełączniki sieci",
    deviceKind: "other",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "Przelaczniki sieci/Przelacznik sieci 4P.svg",
    customWidth: svg300DpiPx(1474),
    customHeight: svg300DpiPx(983),
  },
  {
    templateId: "przelacznik-siec-4p-svg",
    code: "Przełącznik sieć 4P",
    label: "Przełącznik sieć 4P",
    type: "Przełącznik sieci",
    category: "Przełączniki sieci",
    deviceKind: "other",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "Przelaczniki sieci/Przelacznik siec 4P.svg",
    customWidth: svg300DpiPx(829),
    customHeight: svg300DpiPx(983),
  },
  {
    templateId: "rcd-1p-n-new-svg",
    code: "Rozłącznik różnicowoprądowy 1P+N",
    label: "Rozłącznik różnicowoprądowy 1P+N",
    type: "RCD",
    category: "RCD",
    deviceKind: "rcd",
    phase: "L1",
    modules: 2,
    moduleRef: "RCD/Rozłącznik różnicowoprądowy 1P+N.svg",
    customWidth: svg300DpiPx(416),
    customHeight: svg300DpiPx(983),
    rcdRatedCurrent: 40,
    rcdResidualCurrent: 30,
    rcdType: "A",
  },
  {
    templateId: "rcd-3p-n-new-svg",
    code: "Rozłącznik różnicowoprądowy 3P+N",
    label: "Rozłącznik różnicowoprądowy 3P+N",
    type: "RCD",
    category: "RCD",
    deviceKind: "rcd",
    phase: "L1+L2+L3",
    modules: 4,
    moduleRef: "RCD/Rozłącznik różnicowoprądowy 3P+N.svg",
    customWidth: svg300DpiPx(853),
    customHeight: svg300DpiPx(983),
    rcdRatedCurrent: 40,
    rcdResidualCurrent: 30,
    rcdType: "A",
  },
  {
    templateId: "listwa-15-pin-n-svg",
    code: "Listwa 15 pin N",
    label: "Listwa 15 pin N",
    type: "Listwy",
    category: "Listwy do rozdzielnicy",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Listwy do rozdzielnicy/Listwa 15 pin N.svg",
    customWidth: 1243,
    customHeight: 175,
  },
  {
    templateId: "listwa-15-pin-pe-svg",
    code: "Listwa 15 pin PE",
    label: "PE",
    type: "Listwy",
    category: "Listwy do rozdzielnicy",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Listwy do rozdzielnicy/Listwa 15 pin PE.svg",
    customWidth: 1243,
    customHeight: 175,
  },
    {
    templateId: "modul-zabezpieczajacy-svg",
    code: "Moduł zabezpieczający 3P",
    label: "Moduł zabezpieczający 3P",
    type: "Zabezpieczenia",
    category: "Zabezpieczenia",
    deviceKind: "phaseIndicator",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Zabezpieczenia/Moduł zabezpieczający 3P.svg",
    customWidth: svg300DpiPx(209),
    customHeight: svg300DpiPx(983),
  },
  {
    templateId: "lampka-kontrolna-3f-svg",
    code: "Lampka Kontrolna 3 Fazowa",
    label: "Lampka Kontrolna 3 Fazowa",
    type: "Controls",
    category: "Controls",
    deviceKind: "phaseIndicator",
    phase: "L1+L2+L3",
    modules: 1,
    moduleRef: "Kontrolki faz/Lampka Kontrolna 3 Fazowa.svg",
    customWidth: svg300DpiPx(209),
    customHeight: svg300DpiPx(983),
  },
  {
    templateId: "gsu-6-pin-svg",
    code: "GSU 6-zaciskowa",
    label: "GSU (Główna Szyna Uziemiająca)",
    type: "Listwy",
    category: "Listwy do rozdzielnicy",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "GSU/GSU.svg",
    customWidth: 1256,
    customHeight: 166,
  },
  {
    templateId: "listwa-n-12pin-svg",
    code: "Listwa N 12PIN",
    label: "Listwa N 12PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "N",
    modules: 1,
    moduleRef: "Listwy zaciskowe/Listwa N 12PIN.svg",
    customWidth: svg300DpiPx(239),
    customHeight: svg300DpiPx(1018),
  },
  {
    templateId: "listwa-n-15pin-svg",
    code: "Listwa N 15PIN",
    label: "Listwa N 15PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "N",
    modules: 1,
    moduleRef: "Listwy zaciskowe/Listwa N 15PIN.svg",
    customWidth: svg300DpiPx(239),
    customHeight: svg300DpiPx(1243),
  },
  {
    templateId: "listwa-n-7pin-svg",
    code: "Listwa N 7PIN",
    label: "Listwa N 7PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "N",
    modules: 1,
    moduleRef: "Listwy zaciskowe/Listwa N 7PIN.svg",
    customWidth: svg300DpiPx(239),
    customHeight: svg300DpiPx(617),
  },
  {
    templateId: "listwa-pe-12pin-svg",
    code: "Listwa PE 12PIN",
    label: "Listwa PE 12PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "Listwy zaciskowe/Listwa PE 12PIN.svg",
    customWidth: svg300DpiPx(239),
    customHeight: svg300DpiPx(1018),
  },
  {
    templateId: "listwa-pe-15pin-svg",
    code: "Listwa PE 15PIN",
    label: "Listwa PE 15PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "Listwy zaciskowe/Listwa PE 15PIN.svg",
    customWidth: svg300DpiPx(239),
    customHeight: svg300DpiPx(1243),
  },
  {
    templateId: "listwa-pe-7pin-svg",
    code: "Listwa PE 7PIN",
    label: "Listwa PE 7PIN",
    type: "Listwy",
    category: "Listwy zaciskowe",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "Listwy zaciskowe/Listwa PE 7PIN.svg",
    customWidth: svg300DpiPx(239),
    customHeight: svg300DpiPx(617),
  },
  {
    templateId: "zlaczka-5-torowa-svg",
    code: "Złączka 5-torowa",
    label: "Złączka 5-torowa (L1-L2-L3-N-PE)",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "L1+L2+L3",
    modules: 3,
    moduleRef: "Złącza/Złączka 5-torowa (L1-L2-L3-N-PE).svg",
    customWidth: svg300DpiPx(1002),
    customHeight: svg300DpiPx(593),
  },
  {
    templateId: "zlaczka-n-1-zaciskowa-svg",
    code: "Złączka N 1-zaciskowa",
    label: "Złączka N 1-zaciskowa",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "N",
    modules: 1,
    moduleRef: "Złącza/Złączka N 1-zaciskowa.svg",
    customWidth: svg300DpiPx(202),
    customHeight: svg300DpiPx(593),
  },
  {
    templateId: "zlaczka-n-2-zaciskowa-svg",
    code: "Złączka N 2-zaciskowa",
    label: "Złączka N 2-zaciskowa",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "N",
    modules: 1,
    moduleRef: "Złącza/Złączka N 2-zaciskowa.svg",
    customWidth: svg300DpiPx(390),
    customHeight: svg300DpiPx(593),
  },
  {
    templateId: "zlaczka-n-3-zaciskowa-svg",
    code: "Złączka N 3-zaciskowa",
    label: "Złączka N 3-zaciskowa",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "N",
    modules: 1,
    moduleRef: "Złącza/Złączka N 3-zaciskowa.svg",
    customWidth: svg300DpiPx(606),
    customHeight: svg300DpiPx(593),
  },
  {
    templateId: "zlaczka-pe-1-zaciskowa-svg",
    code: "Złączka PE 1-zaciskowa",
    label: "Złączka PE 1-zaciskowa",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "Złącza/Złączka PE 1-zaciskowa.svg",
    customWidth: svg300DpiPx(206),
    customHeight: svg300DpiPx(611),
  },
  {
    templateId: "zlaczka-pe-2-zaciskowa-svg",
    code: "Złączka PE 2-zaciskowa",
    label: "Złączka PE 2-zaciskowa",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "Złącza/Złączka PE 2-zaciskowa.svg",
    customWidth: svg300DpiPx(396),
    customHeight: svg300DpiPx(611),
  },
  {
    templateId: "zlaczka-pe-3-zaciskowa-svg",
    code: "Złączka PE 3-zaciskowa",
    label: "Złączka PE 3-zaciskowa",
    type: "Złącza",
    category: "Złącza",
    deviceKind: "terminalBlock",
    phase: "PE",
    modules: 1,
    moduleRef: "Złącza/Złączka PE 3-zaciskowa.svg",
    customWidth: svg300DpiPx(585),
    customHeight: svg300DpiPx(612),
  },
];

export const groupOrder = [
  "FR",
  "SPD",
  "RCD",
  "MCB",
  "Blok rozdzielczy",
  "Przełączniki sieci",
  "Zabezpieczenia",
  "Controls",
  "Inne",
  "Listwy zaciskowe",
  "Z\u0142\u0105cza",
  "Listwy do rozdzielnicy",
];

export const groupDisplayNames: Record<string, string> = {
  Controls: "Kontrolki faz",
};
